### PR TITLE
+ Create Configuration class and add option `exceptions_to_convert`

### PR DESCRIPTION
**Pull request by PikachuEXE**
* Make method use the option value to rescue
$ Refactor the spec

For #8

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Would anyone be able to review this? :)

**Comment by jipiboily** [comment]
It's in my TODO list, just mad busy, sorry!

**Comment by PikachuEXE** [comment]
No worries, I am also sometimes too busy and sometime free.
And this is done when I am free :P
I might refactor it again tomorrow (not changing the spec)

**Comment by PikachuEXE** [comment]
Periodic PING inbound
@jipiboily PING! :bell:

**Comment by jipiboily** [comment]
@PikachuEXE the code looks sane. Can you tell me what use case or problem this is solving? I guess I don't see or understand the potential use of this :(

**Comment by PikachuEXE** [comment]
For now the gem judges what kind of errors should be rescue (thus the constant list of error classes)
But developers might think some additional classes should be rescued or/and some classes should **not** be rescued.

Something like #6 is a good example.
You can't really know all gems that people are using and catch up with the error classes.
So if they use some gems or custom errors and want those to be rescued by this gem, they can just configure them (without hacking)

**Comment by PikachuEXE** [comment]
Will this be reviewed if rebased?

**Comment by epaulet** [comment]
@PikachuEXE Sorry for the delay. We'll get this reviewed asap.

**Comment by epaulet** [comment]
@PikachuEXE This looks good, thanks. Please resolve conflicts.

**Comment by PikachuEXE** [comment]
CI pass except ruby-head with some strange error
https://travis-ci.org/rainforestapp/http-exceptions/jobs/118134393

Should be safe to ignore it?

**Comment by epaulet** [comment]
Travis uses a version of bundler that has this issue. https://github.com/bundler/bundler/issues/3558

I've solved this before by upgrading bundler in travis.yml:

```
before_install:
  - gem update bundler
```

**Comment by PikachuEXE** [comment]
ruby-head still fails after `gem update bundler`
Saying `Nothing to update`
Their bug?

**Comment by epaulet** [comment]
Seems to be. It probably says `Nothing to update` because bundler is cached. It says it on the successful builds as well.

**Pull request merged**
